# Generated by Django 2.2.6 on 2020-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_set_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cronjob_mail_magazine',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user_admin',
            field=models.BooleanField(default=0),
        ),
    ]
