# Generated by Django 2.2.6 on 2020-03-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200313_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lock_status',
            field=models.CharField(choices=[('LOCKED', 'Account Locked'), ('UNLOCKED', 'Account Unlocked')], default='UNLOCKED', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_login_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
