# Generated by Django 2.2.6 on 2020-03-23 09:45

from django.db import migrations, models
from Users.models import User,UserProfile

def revert_data_sex_colum(apps, schema_editor):
    UserProfile.objects.all().update(sex=1)

class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_account_lock_changes'),
    ]

    operations = [
        migrations.RunPython(revert_data_sex_colum),
        migrations.RenameField(
            model_name='userprofile',
            old_name='position',
            new_name='position_department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user_admin',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_date_joined',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.BooleanField(default=False),
        ),
    ]
