# Generated by Django 2.2.6 on 2020-03-25 07:23

from django.db import migrations, models
from Users.models import UserProfile

def revert_data_sex_colum(apps, schema_editor):
    UserProfile.objects.all().update(sex=1)

class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200323_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
