# Generated by Django 2.2.6 on 2020-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200325_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
