# Generated by Django 2.2.6 on 2020-03-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailMagazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmagazine',
            old_name='vol_version',
            new_name='order',
        ),
    ]
