# Generated by Django 2.2.6 on 2020-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailMagazine', '0002_auto_20200306_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmagazine',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
