# Generated by Django 2.2.6 on 2020-03-04 09:26

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0001_initial'),
        ('Company', '0001_initial'),
        ('Workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_assessment', models.IntegerField(default=1)),
                ('point', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Workshop')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_assessment', models.FloatField(default=1)),
                ('score_listen', models.FloatField(null=True)),
                ('score_ask_questions', models.FloatField(null=True)),
                ('score_advance', models.FloatField(null=True)),
                ('score_retention', models.FloatField(null=True)),
                ('score_sharing_purpose', models.FloatField(null=True)),
                ('score_personal_reciprocal', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_average_score', models.FloatField(null=True)),
                ('total_normdist_score', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Workshop')),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('user', 'workshop', 'company', 'count_assessment')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question', 'workshop', 'company', 'count_assessment')},
        ),
    ]
