# Generated by Django 2.2.6 on 2020-03-04 09:26

import os

import django
from django.db import migrations, models, connection

def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), 'csaplus24_average.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)

   file_path = os.path.join(os.path.dirname(__file__), 'csaplus24_coefficient.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csaplus24Average',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Question.Questions')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A.日常の関わり', 'A.日常の関わり'), ('B.対話力', 'B.対話力')], max_length=20)),
                ('type', models.CharField(choices=[('個別対応', '個別対応'), ('前進', '前進'), ('傾聴', '傾聴'), ('継続', '継続'), ('質問', '質問'), ('目的共有', '目的共有')], max_length=20)),
                ('factor', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'csaplus24_average',
            },
        ),
        migrations.CreateModel(
            name='Csaplus24Coefficient',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Question.Questions')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A.日常の関わり', 'A.日常の関わり'), ('B.対話力', 'B.対話力')], max_length=20)),
                ('type', models.CharField(choices=[('個別対応', '個別対応'), ('前進', '前進'), ('傾聴', '傾聴'), ('継続', '継続'), ('質問', '質問'), ('目的共有', '目的共有')], max_length=20)),
                ('factor', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'csaplus24_coefficient',
            },
        ),
        migrations.RunPython(load_data_from_sql),
    ]
