# Generated by Django 2.2.6 on 2020-03-05 07:16
import os
from django.utils import timezone
from datetime import datetime
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='total_staff',
        ),
        migrations.AddField(
            model_name='company',
            name='date_contract_end',
            field=models.DateTimeField(default=datetime.now(tz=timezone.utc)),
        ),
        migrations.AddField(
            model_name='company',
            name='date_contract_start',
            field=models.DateTimeField(default=datetime.now(tz=timezone.utc)),
        ),
    ]
