# Generated by Django 2.2.6 on 2020-03-06 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20200305_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_contract_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_contract_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
