# Generated by Django 2.2.6 on 2020-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20200306_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
