# Generated by Django 2.2.6 on 2020-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
