# Generated by Django 2.2.6 on 2020-03-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0002_workshop_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
