# Generated by Django 2.2.6 on 2020-03-04 09:26
import os
from django.db import migrations, models, connection

def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), 'oauth2_provider_application.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('oauth2_provider', '__latest__'),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
    ]
