# Generated by Django 2.2.6 on 2020-03-04 09:26
import os

from django.db import migrations, models, connection


def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), 'meanvalue_stddeviation.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeanvalueStddeviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('個別対応', '個別対応'), ('前進', '前進'), ('傾聴', '傾聴'), ('継続', '継続'), ('質問', '質問'), ('目的共有', '目的共有'), ('全体', '全体')], max_length=20)),
                ('average_value', models.FloatField(max_length=25)),
                ('standard_deviation', models.FloatField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meanvalue_stddeviation',
            },
        ),
        migrations.RunPython(load_data_from_sql),
    ]
