# Generated by Django 2.2.6 on 2019-12-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeanvalueStddeviation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meanvaluestddeviation',
            name='average_value',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='meanvaluestddeviation',
            name='standard_deviation',
            field=models.FloatField(max_length=25),
        ),
    ]
